spring.application.name=task-manager-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager

spring.datasource.username=postgres

spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true